name: Publish Package to Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish to GitHub Packages
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        repository-url: https://upload.pypi.org/legacy/
        # For GitHub Packages, uncomment and set GITHUB_TOKEN secret
        # repository-url: https://upload.pypi.org/legacy/
        # username: __token__
        # password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to Private PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        # Uncomment for private PyPI
        # repository-url: https://your-private-pypi.example.com
        # username: __token__
        # password: ${{ secrets.TWINE_USERNAME }}  # or PYPI_TOKEN
        # For PyPI, use:
        repository-url: https://upload.pypi.org/legacy/
        username: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: List built artifacts
      run: ls -la dist/